[alias]
b = "build"
br = "build --release"
c = "check"
t = "test"
r = "run"
rr = "run --release"
bubbles_debug = "r --example bubbles --features=qp_debug"
tiles_debug = "r --example tiles --features=qp_debug"
bubbles = "rr --example bubbles"
tiles = "rr --example tiles"
space_shooter = "r --example space_shooter --features=qp_debug"
