pub extern crate sdl2;
pub extern crate gl;
pub extern crate nalgebra_glm as glm;
pub extern crate freetype as ft;
pub extern crate serde;
// pub extern crate gltf;

pub mod core;
pub mod engine;
pub mod registry;
pub mod components;
pub mod systems;
pub mod wrappers;
pub mod schemas;

pub use components::resources;
// pub use engine::run;
pub use systems::ec_store;
pub use systems::ec_store::Component;
pub use systems::ec_store::EntityManager;
pub use systems::ec_store::VersionedIndex;
pub use core::rendering;
pub use core::math;
pub use core::utils;
pub use engine::QuiPiApp;
pub use engine::DebugInfo;
pub use engine::FrameState;
pub use engine::FrameResponse;
pub use registry::Registry;
pub use wrappers::sdl2::window::QuiPiWindow;
pub use wrappers::opengl;
